FROM jhaas_abs

# when building the image for this docker file, we in fact run a set of tests of the underlying jhaas_abs container!
ARG NB_UID=1000
ARG NB_HOME=/home/jovyan
ARG NB_USER=jovyan
ARG DATA=${NB_HOME}/teaching_MS-MO-ABS/data/
ARG CE_TOUR=bioinftour

USER ${NB_UID}

COPY make_tests .
# execute Unix tests (base conda env)
RUN make -f ~/make_tests test_unix

# execute Bioinformatics Tour (bioinftour conda env)
# Make RUN commands use the new environment:
# append --format docker to the build command, see https://github.com/containers/podman/issues/8477
SHELL ["conda", "run", "-n", "bioinftour", "/bin/bash", "-c"]
WORKDIR "${DATA}"
RUN make -f ~/make_tests test_tour

# execute NGS tests
SHELL ["conda", "run", "-n", "rnaseq", "/bin/bash", "-c"]
WORKDIR "${DATA}"
RUN make -f ~/make_tests test_ngs
