nameprefix: msmoabs
dir_dist: ./no_backup
dir_logs: Logs
dir_benchmarks: Benchmarks
dir_refdata: BioData
proxy: http://proxy.computational.bio.uni-giessen.de:3128
downloads:
  #~ - url: https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR1718832/SRR1718832
    #~ target: RNA_Scr_V1.fq.gz
    #~ target_dir: refdata
    #~ md5: a7c79f1fbd98a7844a8a853b71778404
    #~ type: sra
  #~ - url: https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR1718833/SRR1718833
    #~ target: RNA_Scr_V2.fq.gz
    #~ target_dir: refdata
    #~ md5: 8c5b7ffc140f6fae96b50c361bcfa65f
    #~ type: sra
  #~ - url: https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR1718836/SRR1718836
    #~ target: RNA_Scr_T2.fq.gz
    #~ target_dir: refdata
    #~ md5: 88316f7ecbe9926203a079c2ce44e9fe
    #~ type: sra
  - url: https://sra-pub-run-odp.s3.amazonaws.com/sra/ERR12342748/ERR12342748
    target: 13422.177skin.fq.gz
    target_dir: refdata
    md5: 6783474970c2e024ea155d0206d4e947
    type: sra
