# todo: "make" files once and push around through artifacts!

name: build_container

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - add_build-action

jobs:
  build_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout teaching_MS-MO-ABS repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read image version from dockerfile
        id: vars
        run: |
          VERSION=$(head -n 1 JHaaS/jhaas.dockerfile | cut -d ":" -f 2- | tr -d " ")
          echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV

      - name: Login to computational.bio registry
        uses: docker/login-action@v3
        with:
          registry: harbor.computational.bio.uni-giessen.de
          username: ${{ vars.HARBOR_CB_USERNAME_test }}
          password: ${{ secrets.HARBOR_CB_SECRET_test }}

      - name: prepare image context
        run: |
          mkdir img_context
          cp JHaaS/Tour/env_tour.yaml JHaaS/RNAseq/env_rnaseq.yaml JHaaS/RNAseq/env_dge.yaml JHaaS/NGS/env_ngs.yaml JHaaS/ChIPseq/env_chipseq.yaml JHaaS/jhaas.dockerfile img_context/

      - name: Build JHaaS image and push to harbor.computational.bio.uni-giessen.de registry
        uses: docker/build-push-action@v6
        with:
          context: img_context
          push: true
          file: JHaaS/jhaas.dockerfile
          tags: |
            harbor.computational.bio.uni-giessen.de/tinqiita/jhaas_msmoabs:${{ env.IMAGE_TAG }}
            harbor.computational.bio.uni-giessen.de/tinqiita/jhaas_msmoabs:latest
